name    'fancyguy-l2tp'
version '2.0.7'
author  'Steve Buzonas'
license 'Apache2'
project_page 'https://github.com/slbmeh/puppet-foo'
source  'https://github.com/example42/puppet-foo'
summary 'Puppet module for l2tp'
description 'This module installs and manages l2tp. Check README.rdoc for details. Puppi is required for some common functions: you can install them without using the whole module. Monitor and firewall dependencies are needed only if the relevant features are 
enabled'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
dependency 'lab42/firewall', '>= 2.0.0'
